//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Event_
    {
        public Event_()
        {
            this.UserProfiles = new HashSet<UserProfile>();
            this.Songs = new HashSet<Song>();
        }
        [Key]
        public int Event_Id { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime EventTime { get; set; }
        public int UserID { get; set; }

        [Required(ErrorMessage = "")]
        [Display(Name = "")]
        public string Subjects { get; set; }

        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
        
    }
}
