//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public int SongId { get; set; }
        public string SongName { get; set; }
        public string SongUrl { get; set; }
        public int Event_Id { get; set; }
    
        public virtual Event_ Event_ { get; set; }
    }
}
