//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventsWebApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя или пароль не верны..
        /// </summary>
        public static string addModelError {
            get {
                return ResourceManager.GetString("addModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить трек.
        /// </summary>
        public static string addTrack {
            get {
                return ResourceManager.GetString("addTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив Событий.
        /// </summary>
        public static string archieveEvents {
            get {
                return ResourceManager.GetString("archieveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string archive {
            get {
                return ResourceManager.GetString("archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены?.
        /// </summary>
        public static string areYouSure {
            get {
                return ResourceManager.GetString("areYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны выбрать хотя бы одну тему.
        /// </summary>
        public static string atLeastOneTag {
            get {
                return ResourceManager.GetString("atLeastOneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аватар.
        /// </summary>
        public static string avatar {
            get {
                return ResourceManager.GetString("avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение личных данных.
        /// </summary>
        public static string changePersonalData {
            get {
                return ResourceManager.GetString("changePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение PlayList.
        /// </summary>
        public static string changePlaylist {
            get {
                return ResourceManager.GetString("changePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить профиль.
        /// </summary>
        public static string changeProfile {
            get {
                return ResourceManager.GetString("changeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение аватара.
        /// </summary>
        public static string changingAvatar {
            get {
                return ResourceManager.GetString("changingAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string changingPassword {
            get {
                return ResourceManager.GetString("changingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите темы.
        /// </summary>
        public static string chooseTags {
            get {
                return ResourceManager.GetString("chooseTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите Ваши интересы.
        /// </summary>
        public static string chooseYourInterest {
            get {
                return ResourceManager.GetString("chooseYourInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите новый пароль.
        /// </summary>
        public static string confirnNewPassword {
            get {
                return ResourceManager.GetString("confirnNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать событие.
        /// </summary>
        public static string createEvent {
            get {
                return ResourceManager.GetString("createEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание события.
        /// </summary>
        public static string creatingEvent {
            get {
                return ResourceManager.GetString("creatingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создатель.
        /// </summary>
        public static string creator {
            get {
                return ResourceManager.GetString("creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль.
        /// </summary>
        public static string currentPassword {
            get {
                return ResourceManager.GetString("currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль неверен или новый пароль не корректен..
        /// </summary>
        public static string currentPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("currentPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string entering {
            get {
                return ResourceManager.GetString("entering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите.
        /// </summary>
        public static string enterPlease {
            get {
                return ResourceManager.GetString("enterPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать событие.
        /// </summary>
        public static string eventCreate {
            get {
                return ResourceManager.GetString("eventCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        public static string eventDateTime {
            get {
                return ResourceManager.GetString("eventDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string eventDescription {
            get {
                return ResourceManager.GetString("eventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string eventName {
            get {
                return ResourceManager.GetString("eventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники события.
        /// </summary>
        public static string eventParticipants {
            get {
                return ResourceManager.GetString("eventParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События.
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр события.
        /// </summary>
        public static string eventShow {
            get {
                return ResourceManager.GetString("eventShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно быть датой.
        /// </summary>
        public static string fieldShouldBedate {
            get {
                return ResourceManager.GetString("fieldShouldBedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не менее 6 символов..
        /// </summary>
        public static string minimumLengthPassword {
            get {
                return ResourceManager.GetString("minimumLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самые активные участники.
        /// </summary>
        public static string mostActiveParticipant {
            get {
                return ResourceManager.GetString("mostActiveParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется Имя.
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ближайшие.
        /// </summary>
        public static string nearest {
            get {
                return ResourceManager.GetString("nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ближайшие события.
        /// </summary>
        public static string nearestEvents {
            get {
                return ResourceManager.GetString("nearestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое событие.
        /// </summary>
        public static string newEvent {
            get {
                return ResourceManager.GetString("newEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль и подтверждение не совпадают. .
        /// </summary>
        public static string newPasswordAndConfirmationDoNotMatch {
            get {
                return ResourceManager.GetString("newPasswordAndConfirmationDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количесто Участников.
        /// </summary>
        public static string numberParticipant {
            get {
                return ResourceManager.GetString("numberParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль успешно изменен..
        /// </summary>
        public static string passwordChanged {
            get {
                return ResourceManager.GetString("passwordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля не совпадают..
        /// </summary>
        public static string passwordsDoNotMatch {
            get {
                return ResourceManager.GetString("passwordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно установлен..
        /// </summary>
        public static string passwordSet {
            get {
                return ResourceManager.GetString("passwordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плеер.
        /// </summary>
        public static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование профиля.
        /// </summary>
        public static string profileEdit {
            get {
                return ResourceManager.GetString("profileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string profileName {
            get {
                return ResourceManager.GetString("profileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string repeatPassword {
            get {
                return ResourceManager.GetString("repeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется заполнить поле времени события.
        /// </summary>
        public static string requireToFullfillFieldTimeEvent {
            get {
                return ResourceManager.GetString("requireToFullfillFieldTimeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск событий.
        /// </summary>
        public static string searchEvents {
            get {
                return ResourceManager.GetString("searchEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть профиль.
        /// </summary>
        public static string seeProfile {
            get {
                return ResourceManager.GetString("seeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коротко о Вас:.
        /// </summary>
        public static string shortlyAbout {
            get {
                return ResourceManager.GetString("shortlyAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, ничего не найдено....
        /// </summary>
        public static string sorryNothingHasFound {
            get {
                return ResourceManager.GetString("sorryNothingHasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписаться.
        /// </summary>
        public static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темы.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События и люди.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не короче 6 символов..
        /// </summary>
        public static string tooShortPassword {
            get {
                return ResourceManager.GetString("tooShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить треки.
        /// </summary>
        public static string trackDelete {
            get {
                return ResourceManager.GetString("trackDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название трека.
        /// </summary>
        public static string trackName {
            get {
                return ResourceManager.GetString("trackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url трека.
        /// </summary>
        public static string trackUrl {
            get {
                return ResourceManager.GetString("trackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отписаться.
        /// </summary>
        public static string unSubscribe {
            get {
                return ResourceManager.GetString("unSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить аватар.
        /// </summary>
        public static string uploadAvatar {
            get {
                return ResourceManager.GetString("uploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О пользователе.
        /// </summary>
        public static string userAbout {
            get {
                return ResourceManager.GetString("userAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким именем уже существует. Пожалуйста, выберите другое имя..
        /// </summary>
        public static string userAlreadyExists {
            get {
                return ResourceManager.GetString("userAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать профиль.
        /// </summary>
        public static string userEdit {
            get {
                return ResourceManager.GetString("userEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История участия в событиях:.
        /// </summary>
        public static string userEventsHistory {
            get {
                return ResourceManager.GetString("userEventsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интересы пользователя.
        /// </summary>
        public static string userInterests {
            get {
                return ResourceManager.GetString("userInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр профиля.
        /// </summary>
        public static string watchProfile {
            get {
                return ResourceManager.GetString("watchProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны выбрать хотя бы одну тему.
        /// </summary>
        public static string youMustChooseAtLeastOneTag {
            get {
                return ResourceManager.GetString("youMustChooseAtLeastOneTag", resourceCulture);
            }
        }
    }
}
